[main]
# resolv.conf points at dnscrypt-proxy.
dns=none
rc-manager=unmanaged

[device]
wifi.scan-rand-mac-address=yes

[connection]
wifi.cloned-mac-address=random
ethernet.cloned-mac-address=random
connection.stable-id=${CONNECTION}/${BOOT}
