# Additions to the vendored secureblue blocklists.

# Bluetooth is loaded on demand by bluetooth-on.service.
blacklist bluetooth
blacklist btusb
blacklist btintel

install mei /bin/false
install mei-me /bin/false
install mei_me /bin/false
install mei_hdcp /bin/false
install mei_pxp /bin/false

install eepro100 /bin/false
install evbug /bin/false
install kyrofb /bin/false
install nvidiafb /bin/false
install tdfxfb /bin/false
