-- DMS user keybind overrides (edit via Control Center or dms; do not remove this header)

hl.unbind("ALT + CTRL + Delete")
hl.bind("ALT + CTRL + Delete", hl.dsp.exec_cmd("dms ipc call powermenu toggle"), { description = "dms ipc call powermenu toggle" })
hl.unbind("CTRL + SHIFT + Escape")
hl.bind("CTRL + SHIFT + Escape", hl.dsp.exec_cmd("dms ipc call processlist focusOrToggle"), { description = "dms ipc call processlist focusOrToggle" })
hl.unbind("SUPER + I")
hl.bind("SUPER + I", hl.dsp.exec_cmd("dms ipc call settings toggle"), { description = "Settings: Toggle" })
hl.unbind("SUPER + L")
hl.bind("SUPER + L", hl.dsp.exec_cmd("dms ipc call lock lock"), { description = "dms ipc call lock lock" })
hl.unbind("SUPER + SHIFT + C")
hl.bind("SUPER + SHIFT + C", hl.dsp.exec_cmd("dms color pick"), { description = "Color picker" })
hl.unbind("SUPER + SHIFT + S")
hl.bind("SUPER + SHIFT + S", hl.dsp.exec_cmd("dms screenshot"), { description = "dms screenshot" })
hl.unbind("SUPER + CTRL + I")
hl.bind("SUPER + CTRL + I", hl.dsp.window.move({ workspace = "-1", follow = false }), { description = "Move to Previous (silent)" })
hl.unbind("SUPER + CTRL + Left")
hl.bind("SUPER + CTRL + Left", hl.dsp.focus({ workspace = "-1" }), { description = "Previous Workspace" })
hl.unbind("SUPER + CTRL + Right")
hl.bind("SUPER + CTRL + Right", hl.dsp.focus({ workspace = "+1" }), { description = "Next Workspace" })
hl.unbind("SUPER + CTRL + SHIFT + Left")
hl.bind("SUPER + CTRL + SHIFT + Left", hl.dsp.window.move({ workspace = "e-1" }), { description = "move to workspace e-1 (non-silent)" })
hl.unbind("SUPER + CTRL + SHIFT + Right")
hl.bind("SUPER + CTRL + SHIFT + Right", hl.dsp.window.move({ workspace = "e+1" }), { description = "move to workspace e+1 (non-silent)" })
hl.unbind("SUPER + CTRL + down")
hl.bind("SUPER + CTRL + down", hl.dsp.window.move({ workspace = "+1", follow = false }), { description = "Move to Next (silent)" })
hl.unbind("SUPER + E")
hl.bind("SUPER + E", hl.dsp.exec_cmd("nautilus"))
hl.unbind("SUPER + T")
hl.bind("SUPER + T", hl.dsp.exec_cmd("alacritty"), { description = "Alacritty" })
hl.unbind("SUPER + W")
hl.bind("SUPER + W", hl.dsp.exec_cmd("trivalent"))
hl.unbind("CTRL + ALT + Delete")
hl.unbind("Print")
hl.unbind("SUPER + ALT + L")
hl.unbind("SUPER + ALT + space")
hl.unbind("SUPER + CTRL + up")
hl.unbind("SUPER + D")
hl.unbind("SUPER + SHIFT + Slash")
hl.unbind("SUPER + X")
hl.unbind("SUPER + Slash")
hl.bind("SUPER + Slash", hl.dsp.exec_cmd("dms ipc call keybinds toggle hyprland"), { description = "dms ipc call keybinds toggle hyprland" })
