-- Auto-generated by DMS — do not edit manually

hl.monitor({ output = "", mode = "preferred", position = "0x0", scale = 1 })
hl.monitor({ output = "eDP-2", mode = "2560x1600@165.002", position = "0x0", scale = 1.6, vrr = 2 })
